FROM node

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . /usr/src/app

# App binding port
EXPOSE 3001

RUN export NODE_ENV=prod
CMD ["npm", "start"]
